### PR TITLE
Fix: openvasd doesn't support empty passphrase for usk crendential

### LINKED ISSUE #1831: Empty passphrase sshkey doesnt work with openvasd scanner-api
### Steps to reproduce

1.
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas:** (openvas --version)

**gvm-libs:**

**openvas-smb:**

**ospd-openvas:** (ospd-openvas --version)

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

### Logfiles

```
```

### PR DESCRIPTION
**Pull request by jjnicola**
**What**:
Fix openvasd doesn't support empty passphrase for usk crendential
SC-1233
Close #1831

**Why**:
With an empty password the scan is stored but when the start command is sent, I got the following:
`2025-02-11T15:15:21.349117Z  WARN openvasd::controller::results: results sync failed e=storage error occurred: serialization error`

If the password field is not sent at all, the scan is even not stored, with the following response:
`{"line":1,"column":799,"message":"missing field password at line 1 column 799"}`

**How**:

**Checklist**:

- [ ] Tests
- [ ] PR merge commit message adjusted

### CODE REVIEW

File: rust/src/models/credential.rs [hunk 1]
```diff
@@ -140,7 +143,12 @@ pub enum CredentialType {
         /// The username for authentication.
         username: String,
         /// The password for authentication.
-        password: String,
+        // A key without passphrase can be expected
+        #[cfg_attr(
+            feature = "serde_support",
+            serde(default, flatten, skip_serializing_if = "Option::is_none")
```
Comment (nichtsfrei) [inline rust/src/models/credential.rs:149]: why do you need flatten?

File: rust/src/openvas/pref_handler.rs [hunk 2]
```diff
@@ -419,7 +419,10 @@ where
                         ));
                         credential_preferences.push(format!(
                             "{OID_SSH_AUTH}:2:password:SSH key passphrase:|||{}",
-                            password
+                            match password {
```
Comment (nichtsfrei) [inline rust/src/openvas/pref_handler.rs:422]: why not use `.unwrap_or_default()`?

File: rust/src/osp/commands.rs [hunk 3]
```diff
@@ -308,7 +308,14 @@ fn write_credentials(scan: &Scan, writer: &mut Writer) -> Result<()> {
                         privilege,
                     } => {
                         write_str_element(writer, "username", username)?;
-                        write_str_element(writer, "password", password)?;
+                        write_str_element(
+                            writer,
+                            "password",
+                            match password {
```
Comment (nichtsfrei) [inline rust/src/osp/commands.rs:314]: why not use .unwrap_or_default()?/

File: rust/src/scannerctl/osp/start_scan.rs [hunk 4]
```diff
@@ -570,7 +570,13 @@ impl From<models::Credential> for Credential {
                 privilege,
             } => {
                 credentials.push(("username".to_string(), username));
-                credentials.push(("password".to_string(), password));
+                credentials.push((
+                    "password".to_string(),
+                    match password {
```
Comment (nichtsfrei) [inline rust/src/scannerctl/osp/start_scan.rs:575]: why not use .unwrap_or_default()?

File: rust/src/models/credential.rs (hunk 1 above)
Comment (jjnicola) [reply rust/src/models/credential.rs]: removed flatten. I had c&p the line.

**Review by nichtsfrei — APPROVED** [review]
